---

boot: {}

kernel:
  name: gentoo-sources
  config:
    entries: {}
    default_entries:
      - option: GENTOO_LINUX_INIT_SCRIPT
        after:  GENTOO_LINUX
        value:  False
        enabled: "{{ systemd }}"
      - option: GENTOO_LINUX_INIT_SYSTEMD
        after:  GENTOO_LINUX_UDEV
        enabled: "{{ systemd }}"
      - option: FANOTIFY_ACCESS_PERMISSIONS
        value:  True
        enabled: "{{ systemd }}"
      # TODO: Add kernel options for uefi
