# Apply common configuration to all hosts
- hosts: all
  remote_user: root
  roles:
    - role: common
      tags:
        - always

# Configure `gentoo` hosts
- hosts: gentoo
  remote_user: root
  roles:
    - role: common_linux
      tags:
        - always
    - role: common_gentoo
      tags:
        - always
    - role: create_gentoo
