# Apply common configuration to all hosts
- hosts: all
  remote_user: root
  roles:
    - role: common

# Configure `gentoo` hosts
- hosts: gentoo
  remote_user: root
  roles:
    - role: common_linux
    - role: common_gentoo
    - role: create_gentoo
