# Apply common configuration to all hosts
- hosts: all
  remote_user: "{{ user }}"
  roles:
    - role: common

# Configure `gentoo` hosts
- hosts: gentoo
  remote_user: "{{ user }}"
  roles:
    - role: common_linux
    - role: common_gentoo
    - role: setup_gentoo
