---

# TODO: fix file

# Cosi' funziona per local e gentoo
- name: Setup repos.conf
  template:
    src:   /repos/gentoo.conf.j2
    dest:  /etc/portage/repos.conf/gentoo.conf

- name: Setup repos.conf
  template:
    src:   /repos/local.conf
    dest:  /etc/portage/repos.conf/local.conf

# Crossdev
# root #mkdir -p /usr/local/portage-crossdev/{profiles,metadata}
# root #echo 'crossdev' > /usr/local/portage-crossdev/profiles/repo_name
# root #echo 'masters = gentoo' > /usr/local/portage-crossdev/metadata/layout.conf
# root #chown -R portage:portage /usr/local/portage-crossdev
# If the main Portage tree is synchronized by using Git, or any other method with Manifest files that do not include checksums for ebuilds, prevent "masked by: corruption" errors with:

# FILE /usr/local/portage-crossdev/metadata/layout.conf
# masters = gentoo
# thin-manifests = true
# Then instruct Portage and crossdev to use this overlay:

# FILE /etc/portage/repos.conf/crossdev.conf
# [crossdev]
# location = /usr/local/portage-crossdev
# priority = 10
# masters = gentoo
# auto-sync = no

- name: Update GCC version
 command: gcc-config 1 # TODO: Choose based on CHOST

- name: Update environment
  command: eselect env update
  tags:
    - environment
