---

- command: systemctl enable systemd-networkd systemd-resolved avahi-daemon
  when: "{{ systemd }}"

- command: systemctl restart systemd-networkd systemd-resolved avahi-daemon
  when: "{{ systemd }}"

- command: ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
  when: "{{ systemd }}"

- name: Select profile
  eselect_profile:
    arch:      "{{ arch                      }}"
    multilib:  "{{ multilib  | default(omit) }}"
    hardened:  "{{ hardened  | default(omit) }}"
    systemd:   "{{ systemd   | default(omit) }}"
    selinux:   "{{ selinux   | default(omit) }}"
    developer: "{{ developer | default(omit) }}"
    desktop:   "{{ desktop   | default(omit) }}"

- name: Sync repository
  command: emerge --sync

- name: Setup local portage repository (1/4)
    path: /usr/local/portage/metadata
    state: directory

- name: Setup local portage repository (2/4)
  template:
    src:  local_repository/layout.conf
    dest: /usr/local/portage/layout.conf

- name: Setup local portage repository (3/4)
  template:
    src:  local_repository/repo_name
    dest: /usr/local/portage/repo_name

- name: Setup local portage repository (4/4)
  command: chown -R portage:portage /usr/local/portage
