---

- command: systemctl enable systemd-networkd
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl enable systemd-resolved 
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl enable avahi-daemon
  when: "{{ systemd is defined }}"
  tags: service

- command: # TODO: Add wired.network config file
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl restart systemd-networkd
  when: "{{ systemd is defined }}"
  tags: service

- command: systemctl restart systemd-resolved 
  when: "{{ systemd is defined }}"
  tags: service

- command: # TODO: Add /etc/nsswitch.conf config file
  when: "{{ systemd is defined }}"
  tags: service
  # files mdns4_minimal [NOTFOUND=return] dns mdns4

- command: emerge net-dns/avahi sys-auth/nss-mdns

- command: systemctl restart avahi-daemon
  when: "{{ systemd is defined }}"
  tags: service
  

- command: ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-hostname kate # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-chassis laptop # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- command: hostnamectl set-deployment production # TODO: replace with customized value
  when: "{{ systemd is defined }}"
  tags: service

- name: Update packages
  portage:
    package: "@world"
    update:  "yes"
    deep:    "yes"
    sync:    "yes"
  tags: sync

- name: Setup local portage repository (1/4)
  file:
    path:  /usr/local/portage/metadata
    state: directory
  tags: repository

- name: Setup local portage repository (2/4)
  template:
    src:  portage/local_repository/layout.conf.j2
    dest: /usr/local/portage/metadata/layout.conf
  tags: repository

- name: Setup local portage repository (3/4)
  template:
    src:  portage/local_repository/repo_name.j2
    dest: /usr/local/portage/repo_name
  tags: repository

- name: Setup local portage repository (4/4)
  command: chown -R portage:portage /usr/local/portage
  tags: repository

- name: Install basic software
  portage:
    package: "{{ item }}"
    state:   installed
    update:  "yes"
  with_items: "{{ packages.basic }}"
  tags: install
