- name: Install Portage
  command: "{{ '/usr/bin/emerge-webrsync' | chrooted('/mnt/gentoo') }}"

- name: Select profile
  eselect_profile:
    arch:      "{{ sys.arch }}"
    hardened:  "{{ sys.hardened | default(omit) }}"
    multilib:  "{{ sys.multilib | default(omit) }}"
    systemd:   "{{ systemd      | default(omit) }}"
    selinux:   "{{ selinux      | default(omit) }}"
    developer: "{{ developer    | default(omit) }}"
    desktop:   "{{ desktop      | default(omit) }}"
    chroot: /mnt/gentoo

- name: Sync repository
  command: "{{ 'emerge --sync' | chrooted('/mnt/gentoo') }}"

- name: Fix udev version
  command: "{{ 'emerge --deselect sys-fs/udev' | chrooted('/mnt/gentoo') }}"
  when: "{{ sys.systemd }}"
