- name: Install kernel sources
  command: "{{ '%s %s' | format('emerge', kernel.name) |
               chrooted('/mnt/gentoo') }}"

- name: Remove existing kernel configuration
  file:
    path:  /mnt/gentoo/usr/src/linux/.config
    state: absent

- name: Configure kernel (use default configuration) (1/2)
  make:
    task:     defconfig
    work_dir: /usr/src/linux
    chroot:   /mnt/gentoo
  when: "{{ not 'path' in kernel.config }}"

- name: Configure kernel (use custom configuration) (1/2)
  template:
    src:  "{{ kernel.config.path }}"
    dest: /mnt/gentoo/usr/src/linux/.config
  when: "{{ 'path' in kernel.config }}"

- name: Configure kernel (add custom entries) (2/2)
  kernel_config:
    kernel_dir: /mnt/gentoo/usr/src/linux
    option:     "{{ item.option                    }}"
    value:      "{{ item.value     | default(omit) }}"
    as_module:  "{{ item.as_module | default(omit) }}"
    kind:       "{{ item.kind      | default(omit) }}"
    after:      "{{ item.after     | default(omit) }}"
  when: "{{ item.enabled | default(True) }}"
  with_items: "{{ kernel.config.default_entries |
                  map_merge(kernel.config.entries, 'match_key', 'option') }}"

- name: Compile kernel (1/3)
  make:
    opts:     "{{ kernel.make_opts | default(omit) }}"
    work_dir: /usr/src/linux
    chroot:   /mnt/gentoo

- name: Compile kernel (install modules) (2/3)
  make:
    task:     modules install
    work_dir: /usr/src/linux
    chroot:   /mnt/gentoo

- name: Compile kernel (generate image) (3/3)
  make:
    task:     install
    work_dir: /usr/src/linux
    chroot:   /mnt/gentoo
