#- name: Install kernel sources
#  command: "{{ kernel.name | emerge() | chrooted() }}"

- name: Configure kernel (use default configuration) (1/2)
  command: "{{ 'defconfig' | make_kernel() | chrooted() }}"
  when: "{{ not 'path' in kernel.config }}"

- name: Configure kernel (use custom configuration) (1/2)
  template:
    src: "{{ kernel.config.path }}"
    dest: /mnt/gentoo/usr/src/linux/.config
  when: "{{ 'path' in kernel.config }}"

#- name: Configure kernel (add custom entries) (2/2)
#  kernel_config:
#    kernel_dir: /mnt/gentoo/usr/src/linux
#    option:     "{{ item.name }}"
#    as_module:  "{{ item.as_module | default(false) }}"
#    value:      "{{ item.value }}"
#    kind:       "{{ item.kind | default(omit) }}"
#    after:      "{{ item.enable_after | default(omit) }}"
#  with_items: "{{ kernel.config.entries }}"
#  when: "{{ 'entries' in kernel.config }}"

- name: Compile kernel (1/3)
  command: "{{ kernel.make_opts | default('') | make_kernel() | chrooted() }}"

- name: Compile kernel (install modules) (2/3)
  command: "{{ 'modules install' | make_kernel() | chrooted() }}"

- name: Compile kernel (generate image) (3/3)
  command: "{{ 'install' | make_kernel() | chrooted() }}"
